name: weight_tracker
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  cloud_firestore: ^3.1.10
  dartz: ^0.10.1
  equatable: ^2.0.3
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  fluttertoast: ^8.0.9

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  get_it: ^7.2.0
  json_annotation: ^4.4.0
  logger: ^1.1.0
  provider: ^6.0.1

flutter:

  uses-material-design: true
